### ISSUE TITLE
How Use ToastrNotification

### ISSUE THREAD

**Issue by DTHerrera** [RaphaelNFreitas/ToastrNotification#1]
Hello, you can give me an example of how to use ToastrNotification in my core ASP.NET project

**Comment by RaphaelNFreitas** [comment]
Hello, are you using an ASP.NET CORE? This project is referenced only for FULL FRAMEWORK, if you are using DOT.NET CORE use this project: https://github.com/RaphaelNFreitas/NToastNotify

**Comment by DTHerrera** [comment]
hello, Yes I'm using ASP.NET Core, thank you friend, I'll explore with NToastNotify
